services:
  redis:
    container_name: my-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aknur.taubay
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  postgres:
    driver: local
