name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: npm ci
      - name: Build project
        uses: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files

