name: Print Pull Request Context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, reopened]
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print context
        run: echo "${{ toJSON(github.event) }}"